### ISSUE TITLE
First Version

### ISSUE THREAD

**Issue by dbpolito** [kool-dev/healthz#1]
Kubernetes has a feature called `livenessProbe` which you can provide a TCP, HTTP or EXEC to run in order to check if your application is health or not, it works great but you only have 1 check.

Let's say you need to check both a TCP and a COMMAND, or you create a bash that does the TCP check and the COMMAND or you just 😭 (which i'm doing right now).

The idea here is create a very simple microservice where you basically start a web server with:

```bash
healthz '[{"name": "a", "type": "tcp", "value": "localhost:80"}, {"name": "b", "type": "http", "value": "https://url.com"}, {"name": "c", "type": "exec", "value": "ls -lah /"}]'
```

Which if you access `/` route it will loop into the checkers and return `200 OK` if all checks passed and a `400 Bad Request` if a service fails with return: `[{"name": "c", "message": "Why failed"}]`

The idea is to start simple with these 3 checkers (tcp, http, exec) and add more checkers afterwards.

Related Issue: https://github.com/kubernetes/kubernetes/issues/37218

**Comment by nkabz** [comment]
Good reference -> https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/

**Comment by nkabz** [comment]
Just an update on this issue, scope changed from spinning up a Web server, to just a CLI that outputs if the checks are healthy.

### First Version TODO 💉 **HEALTHZ**
- [x] First version CLI
  - [x] Create Project With [Kool ](www.github.com/kool-dev/kool)CLI Preset
    - [x] Read Json input specified by the user
    - [x] Perform checks on the specified json string
      - [x] TCP
      - [x] HTTP
      - [x] Exec
     - [x] Add tests for each check
       - [x] TCP
       - [x] HTTP
       - [x] Exec
- [ ] Documentation
